// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CEG_DAL.Models;

public partial class Enroll
{
    public int EnrollId { get; set; }

    public int StudentId { get; set; }

    public int ClassId { get; set; }

    public int TransactionId { get; set; }

    public DateTime RegistrationDate { get; set; }

    public DateTime EnrolledDate { get; set; }

    public string Status { get; set; }

    public virtual Class Class { get; set; }

    public virtual Student Student { get; set; }

    public virtual Transaction Transaction { get; set; }
}