// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CEG_DAL.Models;

public partial class Schedule
{
    public int ScheduleId { get; set; }

    public int SessionId { get; set; }

    public int ClassId { get; set; }

    public string DayOfWeek { get; set; }

    public TimeOnly? StartTime { get; set; }

    public TimeOnly? EndTime { get; set; }

    public string Status { get; set; }

    public virtual Class Class { get; set; }

    public virtual Session Session { get; set; }
}