// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CEG_DAL.Models;

public partial class Student
{
    public int StudentId { get; set; }

    public int ParentId { get; set; }

    public int AccountId { get; set; }

    public string Description { get; set; }

    public int? CurLevel { get; set; }

    public int? Age { get; set; }

    public DateTime? Birthdate { get; set; }

    public string Image { get; set; }

    public virtual Account Account { get; set; }

    public virtual ICollection<Enroll> Enrolls { get; set; } = new List<Enroll>();

    public virtual Parent Parent { get; set; }

    public virtual ICollection<StudentProgress> StudentProgresses { get; set; } = new List<StudentProgress>();
}