// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CEG_DAL.Models;

public partial class Teacher
{
    public int TeacherId { get; set; }

    public int AccountId { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Certificate { get; set; }

    public string Address { get; set; }

    public string Image { get; set; }

    public virtual Account Account { get; set; }

    public virtual ICollection<Class> Classes { get; set; } = new List<Class>();
}