// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CEG_DAL.Models;

public partial class Transaction
{
    public int TransactionId { get; set; }

    public int ParentId { get; set; }

    public string VnpayId { get; set; }

    public int TransactionAmount { get; set; }

    public DateTime TransactionDate { get; set; }

    public string TransactionStatus { get; set; }

    public string TransactionType { get; set; }

    public DateTime ConfirmDate { get; set; }

    public virtual ICollection<Enroll> Enrolls { get; set; } = new List<Enroll>();

    public virtual Parent Parent { get; set; }
}